import type { Metadata } from "next";
import { Inter, Darker_Grotesque } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const grotesque = Darker_Grotesque({
  subsets: ["latin"],
  variable: "--font-grotesque",
});

const editorsNote = localFont({
  src: [
    {
      path: "../../public/fonts/editors-note/EditorsNote-Regular-iF664322be6e849.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/editors-note/EditorsNote-Bold-iF664322be38357.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-editorsnote",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${grotesque.variable} ${editorsNote.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
